# permissions for end users to view standalones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: standalone-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: standalone-viewer-role
rules:
- apiGroups:
  - redis.cola.redis
  resources:
  - standalones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.cola.redis
  resources:
  - standalones/status
  verbs:
  - get
