apiVersion: redis.cola.redis/v1
kind: Standalone
metadata:
  labels:
    app.kubernetes.io/name: standalone
    app.kubernetes.io/instance: standalone-sample
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder
  name: standalone-sample
spec:
  RedisConfig:

  KubernetesConfig:
  