apiVersion: redis.cola.redis/v1
kind: Standalone #缩写为rs
metadata:
  name: standalone-sample
spec:
  KubernetesConfig:
    image: m.daocloud.io/quay.io/opstree/redis:v5.0.0
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi